// SEO Metadata for IPTV subscription page - High Impact 2026 Version
export const seoMetadata = {
  title: 'Best IPTV Subscription Plan for Live TV & Sports [2026] - ProStream Space',
  description: '🔥 Subscribe now to our 2026–approved live TV & sports IPTV subscription! 5,000+ global channels, 4K UHD, multi‑device support (Smart TV, Fire TV, Android, iOS, Windows, macOS). 7–30 day trials, fast activation, 99.9% uptime, 24/7 support. Best value & ROI for sports fans, movie lovers, & expats worldwide. No hidden fees, flexible plans. Sign up now and start streaming!',
  keywords: [
    'best iptv subscription plan for live tv and sports 2026',
    'best iptv subscription live tv sports 2026',
    'best iptv sports subscription plan 2026',
    'live tv iptv 2026 subscription high quality',
    'best iptv packages for streaming [country] 2026',
    'best iptv sports packages 2026 global channels',
    'best iptv live tv sports subscription cheap',
    'best iptv plan for live tv and sports 2026',
    'iptv streaming services 2026 best value',
    'cheap iptv subscription for sports 2026',
    'fastest iptv for live tv and sports 2026',
    'best iptv bundle for sports and movies 2026',
    'best iptv provider for live tv and sports 2026',
    'live sports iptv subscription cheap 2026',
    'best iptv services for live tv and sports 2026',
    'best budget iptv for live tv and sports 2026',
    'best premium iptv subscription for live tv and sports 2026',
    'best wd iptv for live tv and sports 2026',
    'best 4k iptv subscription for live tv and sports 2026',
    'best iptv app for live tv and sports 2026',
    'best iptv services to watch live tv and sports 2026',
    'best iptv channels for live tv and sports [country] 2026',
    'best iptv box subscription for live tv and sports 2026',
    'best iptv for firestick [country] [brand] 2026',
    'best iptv for android tv live tv and sports 2026',
    'best iptv for smart tv live tv and sports 2026',
    'best uk iptv subscription for live tv and sports 2026',
    'best us iptv subscription for live tv and sports 2026',
    'best de iptv subscription for live tv and sports 2026',
    'best spain iptv subscription for live tv and sports 2026',
    'best fr iptv subscription for live tv and sports 2026',
    'best bd iptv subscription for live tv and sports 2026',
    'best br iptv subscription for live tv and sports 2026',
    'best mx iptv subscription for live tv and sports 2026',
    'best iptv streaming online 2026',
    'best international iptv for live tv and sports 2026',
    'best 30 day iptv trial for live tv and sports 2026',
    'best iptv app free trial for live tv and sports 2026',
    'best iptv for europe live tv and sports 2026',
    'best iptv for africa live tv and sports 2026',
    'best iptv for asia live tv and sports 2026',
    'best iptv for americas live tv and sports 2026',
    'best iptv for south america live tv and sports 2026',
    'best iptv for north america live tv and sports 2026',
    'best iptv for global live tv and sports 2026',
    'best app for iptv live tv and sports 2026',
    'best package for iptv live tv and sports 2026',
    'best value iptv for live tv and sports 2026'
  ],
  openGraph: {
    title: '🔥 Best IPTV Subscription for Live TV & Sports [2026] - 5,000+ Channels | ProStream Space',
    description: '🔥 Stream 5,000+ global channels, live sports, movies & series in 4K UHD anytime, anywhere on all devices. Versus built to fly for sports & value. Great answer for impulse and loyal watchers. No hidden fees; trial & benefits countdown to sign‑up. Free installation guides. 7–30 day trials, fast activation, 99.9% uptime, 24/7 support. #IPTV #LiveTV #Sports.',
    images: ['/images/landing/iptv-hero.jpg'],
    type: 'website',
    siteName: 'ProStream Space'
  },
  twitter: {
    card: 'summary_large_image',
    title: '🔥 Best IPTV Subscription for Live TV & Sports [2026] - 5,000+ Channels | ProStream Space',
    description: '🔥 Stream 5,000+ global channels, live sports, movies & series in 4K anytime, anywhere on all devices. Versus built to fly for value. Decaying tier‑1 deliverables. Trial sign‑up channel. Free installation guides. 7–30 day trials, 99.9% uptime. #IPTV #LiveTV #Sports.',
    images: ['/images/landing/iptv-hero.jpg']
  },
  canonical: 'https://prostream.space/best-iptv-live-sports-subscription-plan',
  site: {
    name: 'ProStream Space',
    handle: '@ProStreamSpace'
  },
  contacts: {
    email: 'support@prostream.space',
    telegram: '@prostreamspace',
    whatsapp: '+1234567890',
    phone: '+1-800-PROSTREAM'
  }
};
